name: 🐞 バグ報告 (日本語)
description: 不具合を報告する
title: "[Bug] "
labels: ["bug"]

body:

  - type: input
    id: version
    attributes:
      label: Version
      description: 使用している commit ID (hash)。不明な場合は「YYYY-MM-DD 時点の最新版」でも可
      placeholder: "例: a1b2c3d"
    validations:
      required: true

  - type: input
    id: area
    attributes:
      label: エリア (何処のバグか)
      description: highlight / install / config など
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 再現方法
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 想定していた動作
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 実際の動作
    validations:
      required: true

  - type: textarea
    id: plugins
    attributes:
      label: 関連するプラグイン

  - type: textarea
    id: os
    attributes:
      label: OS情報など
      placeholder: |
        OS:
        Neovim:
        その他:

  - type: textarea
    id: notes
    attributes:
      label: その他備考 (optional)
