name: ✨️ 新機能提案 (日本語)
description: 新しい機能の提案
title: "[Feature] "
labels: ["enhancement"]

body:

  - type: textarea
    id: content
    attributes:
      label: 内容
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 理由 / 使うケース
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: その他備考 (optional)
