name: ✨️ Feature Request (English)
description: Suggest a new feature
title: "[Feature] "
labels: ["enhancement"]

body:

  - type: textarea
    id: content
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason / Use Case
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes (optional)
